<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE book [
  <!ELEMENT book (title, dc:title, titleabbrev, info, dedication, preface, chapter, appendix)>
  <!ATTLIST book xmlns CDATA #REQUIRED>
  <!ATTLIST book xmlns:dc CDATA #REQUIRED>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT dc:title (#PCDATA)>
    <!ELEMENT titleabbrev (#PCDATA)>
    <!ELEMENT info (legalnotice, author)>
      <!ELEMENT legalnotice (para)>
      <!ELEMENT para (#PCDATA)>
      <!ELEMENT author (personname)>
      <!ELEMENT personname (firstname, surname)>
      <!ELEMENT firstname (#PCDATA)>
      <!ELEMENT surname (#PCDATA)>
    <!ELEMENT dedication (para)>
    <!ELEMENT preface (title, para)>
    <!ELEMENT chapter (title, para)>
    <!ELEMENT appendix (title, para)>

]>
<book xmlns='http://docbook.org/ns/docbook'
	xmlns:dc='https://www.dublincore.org/specifications/dublin-core/dcmi-terms/'>
	<!-- 
		Ici, le vocabulaire book est celui utiisé par défaut :  
		le namespace déclaré (xmlns) n'a pas d'alias (préfixe balise) donc les balise sans préfixe devront TOUTES 
		faire partie du vocabulaire book
	-->
	<title>An Example Book</title>
	<dc:title>DC title </dc:title>
	<titleabbrev>Example</titleabbrev>
	<info>
		<legalnotice>
			<para>No notice is required.</para>
		</legalnotice>
		<author>
			<personname>
				<firstname>Norman</firstname>
				<surname>Walsh</surname>
			</personname>
		</author>
	</info>
	<dedication>
		<para>This book is dedicated to you.
		</para>
	</dedication>
	<preface>
		<title>Foreword</title>
		<para>Some content is always required.
		</para>
	</preface>
	<chapter>
		<title>A Chapter</title>
		<para>Content is required in chapters too.
		</para>
	</chapter>
	<appendix>
		<title>Optional Appendix</title>
		<para>Appendixes are optional.
		</para>
	</appendix>
</book>