=== nicoduflot/2023-11-27-XML/05-dtd-externe.dtd
<!ELEMENT rolodex (contact*)>
        <!ELEMENT contact (nom, prenom*, adresses, emails)>
        <!ATTLIST contact type (physique|morale) "physique">
            <!ELEMENT nom (#PCDATA)>
            <!ELEMENT prenom (#PCDATA | surnom)*>
                <!ELEMENT surnom (#PCDATA)>
            <!ELEMENT adresses (adresse*)>
                <!ELEMENT adresse (numero, voie, codepostal, ville, pays)>
                <!ATTLIST adresse type (facturation|livraison) #REQUIRED>
                    <!ELEMENT numero (#PCDATA)>
                    <!ELEMENT voie (#PCDATA)>
                    <!ATTLIST voie type (rue | avenue | boulevard | impasse | place | faubourg | route | chemin | voie) #REQUIRED>
                    <!ELEMENT codepostal (#PCDATA)>
                    <!ELEMENT ville (#PCDATA)>
                    <!ELEMENT pays (#PCDATA)>
                    <!ATTLIST pays codeLang (fr-FR|en-US) #REQUIRED>
            <!ELEMENT emails (email+)>
                <!ELEMENT email (#PCDATA)>
                <!ATTLIST email type (personnel|professionel) "personnel">

=== nicoduflot/2023-11-27-XML/05-dtd-externe.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- Déclaration des DTD -->
<!DOCTYPE rolodex SYSTEM "05-dtd-externe.dtd">
<!-- 
   rue | avenue | boulevard | impasse | place | faubourg | route | chemin | voie 
-->
<!-- le xml -->
<rolodex>
    <!-- une entrée du carnet de contacts -->
    <contact type="physique">
        <nom>Durand</nom>
        <prenom>
            Jean
            <surnom>Jojo</surnom>
        </prenom>
        <adresses>
            <adresse type="facturation">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codepostal>75015</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR">FRANCE</pays>
            </adresse>
            <adresse type="livraison">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codepostal>75015</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR"></pays>
            </adresse>
            <adresse type="livraison">
                <numero>1</numero>
                <voie type="rue">Rue de la paix</voie>
                <codepostal>75001</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR">FRANCE</pays>
            </adresse>
        </adresses>
        <emails>
            <email type="personnel">jean.durand@yahoo.fr</email>
            <email type="professionel">jdurand@acme.com</email>
        </emails>
    </contact>
    <contact type="morale">
        <nom>Acme Inc.</nom>
        <adresses>
            <adresse type="facturation">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codepostal>75015</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR">FRANCE</pays>
            </adresse>
            <adresse type="livraison">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codepostal>75015</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR">FRANCE</pays>
            </adresse>
            <adresse type="livraison">
                <numero>14</numero>
                <voie type="place">Place des États-unis</voie>
                <codepostal>75016</codepostal>
                <ville>Paris</ville>
                <pays codeLang="fr-FR">FRANCE</pays>
            </adresse>
        </adresses>
        <emails>
            <email type="professionel">contact@acme.com</email>
            <email type="professionel">sav@acme.com</email>
            <email type="professionel">evenenement@acme.com</email>
        </emails>
    </contact>
</rolodex>
