=== nicoduflot/2023-11-27-XML/08-xpath.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- balises isolées enfants direct de personne -->
    
    <xsd:element name="nom" type="xsd:string"/>
    <xsd:element name="prenom" type="xsd:string"/>

    <!-- balises enfants directs d'adresse -->

    <xsd:element name="numero" type="xsd:string"/>
    <xsd:element name="voie">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="type">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="impasse"/>
                                <xsd:enumeration value="avenue"/>
                                <xsd:enumeration value="rue"/>
                                <xsd:enumeration value="route"/>
                                <xsd:enumeration value="chemin"/>
                                <xsd:enumeration value="place"/>
                                <xsd:enumeration value="faubourg"/>
                                <xsd:enumeration value="boulevard" />
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="codePostal" type="xsd:string"/>
    <xsd:element name="ville" type="xsd:string"/>
    <xsd:element name="pays" type="xsd:string"/>

    <!-- balises enfants directs de telephones -->

    <xsd:element name="telephone">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="type">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="fixe"/>
                                <xsd:enumeration value="bureau"/>
                                <xsd:enumeration value="portable"/>
                                <xsd:enumeration value="professionnel"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <!-- balises enfants directs d'emails -->

    <!-- 
        avoir une restriction sur le format d'mail et l'ajouter à la restriction du contenu de l'attribut type
    -->
    <xsd:simpleType name="formatEmail">
        <xsd:restriction base="xsd:token">
            <xsd:maxLength value="254"/>
            <xsd:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="email">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="formatEmail">
                    <xsd:attribute name="type">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="personnel"/>
                                <xsd:enumeration value="professionnel"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <!-- balise adresse -->

    <xsd:element name="adresse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="numero" />
                <xsd:element ref="voie" />
                <xsd:element ref="codePostal" />
                <xsd:element ref="ville" />
                <xsd:element ref="pays" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- balise telephones -->

    <xsd:element name="telephones">
        <xsd:complexType>
            <xsd:choice>
                <xsd:element ref="telephone" maxOccurs="unbounded" />
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>

    <!-- balise emails -->

    <xsd:element name="emails">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="email" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- balise personne -->
    <xsd:element name="personne">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nom" />
                <xsd:element ref="prenom" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="adresse" />
                <xsd:element ref="telephones" />
                <xsd:element ref="emails" />                
            </xsd:sequence>
            <!-- définir l'attribut type -->
            <xsd:attribute name="type">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="physique"/>
                        <xsd:enumeration value="morale"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <!-- balise racine repertoire -->

    <xsd:element name="repertoire">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="personne" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== nicoduflot/2023-11-27-XML/08-xpath.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<repertoire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="08-xpath.xsd">
    <!-- Amélia EARHART -->
    <personne type="physique">
        <nom>EARHART</nom>
        <prenom>Amélia</prenom>
        <adresse>
            <numero>28</numero>
            <voie type="avenue">avenue de la république</voie>
            <codePostal>66002</codePostal>
            <ville>Atchinson</ville>
            <pays>USA</pays>
        </adresse>
        <telephones>
            <telephone type="bureau">04 05 06 07 08</telephone>
            <telephone type="bureau">04 05 06 07 08</telephone>
        </telephones>
        <emails>
            <email type="professionnel">aearhart@flytogether.com</email>
        </emails>
    </personne>
    <!-- John WALKER -->
    <personne type="physique">
        <nom>WALKER</nom>
        <prenom>John</prenom>
        <adresse>
            <numero>7</numero>
            <voie type="impasse">impasse du chemin</voie>
            <codePostal>75015</codePostal>
            <ville>PARIS</ville>
            <pays>FRANCE</pays>
        </adresse>
        <telephones>
            <telephone type="fixe">01 02 03 04 05</telephone>
            <telephone type="portable">06 07 08 09 10</telephone>
        </telephones>
        <!-- commentaire haha -->
        <emails>
            <email type="personnel">john.walker@wanadoo.fr</email>
            <email type="professionnel">john.walker@texas-ranger.com</email>
        </emails>
    </personne>
    <!-- ACME Inc. -->
    <personne type="morale">
        <nom>ACME Inc.</nom>
        <adresse>
            <numero>7</numero>
            <voie type="impasse">impasse du chemin</voie>
            <codePostal>75015</codePostal>
            <ville>PARIS</ville>
            <pays>FRANCE</pays>
        </adresse>
        <telephones>
            <telephone type="fixe">01 02 03 04 05</telephone>
            <telephone type="portable">06 07 08 09 10</telephone>
        </telephones>
        <emails>
            <email type="personnel">john.walker@wanadoo.fr</email>
            <email type="professionnel">john.walker@texas-ranger.com</email>
        </emails>
    </personne>
</repertoire>
<!-- XPATH -->
<!-- 
    C'est un moyen de cibler un élément dans "l'arbre XML"

    Chemins absolus et relatifs

    Absolu

    on part de la racine vers un élément du document (xml, html)
    ici /repertoire est le départ (la racine) du chemin xpath en absolu
    Si je veux récupérer toutes les balises téléphone avec l'attribut type="fixe"

    racine répertoire
        noeud enfant personne
            noeud enfant telephones
                noeuds enfants telephone avec type="fixe"

    /repertoire/personne/telephones/telephone type="fixe"

    Relatif

    on ne part pas de la racine mais d'un élément (noeud) déterminé, et en empruntant des axes, on récupère les informations selon des directive précises

    retrouver les noms des personnes ayant un numéro de téléphone avec type="portable"

    noeud telephone type="portable"
        remonter au noeud parent telephones
            aller sur le noeud frère nom

    telephone type="portable" => axe noeud parent = noeud frère nom 

    On localise alors les données par :
        - un axe (la direction d'un endroit vers un autre, vers les ancètres, les descendants ou les frères et soeurs)
        - un noeud ciblé
        - facultatif : un ou plusieurs prédicats => des condition sur le noeud ciblé / parcourus
            - les attributs (présence, non présence + valeur donnée ou liste de valeurs données )
            - la position (nième, le premier, le dernier, etc.)

    axe::noeud[predicat][predicat]...[predicat]/axe::noeud[predicat][predicat]...[predicat]

    exemple de chemin absolu

    depuis le xml repertoire, repérer en chemin absolu le pays où vivent les personnes

    1 noeud répertoire
    2 noeud personne
    3 noeud adresse
    4 noeud pays

    chaque étape au format xpath

    1 child::repertoire
    2 child::personne
    3 child::adresse
    4 child::pays

    le chemin complet en xpath

    /child::repertoire/child::personne/child::adresse/child::pays

    child c'est la direction (l'axe) par défaut, on peut ne pas l'écrire

    /repertoire/personne/adresse/pays

    depuis la racine, repérer tous les commentaires des noeuds descendants

    /descendant::comment()

    depuis la racine, repérer tous les contenus texte des noeuds descendants
    /descendant::text()

    exemple de chemin relatif

    depuis telephones, repérer le pays indiqué dans adresse
    1 remonter  au noeud frère précédent adresse
    2 descendre au noeud enfant pays

    /descendant-or-self::node()/telephones/preceding-sibling::adresse/pays

    on va devoir dire à xpath, sur XML Copy editor, que l'on part des descendants du noeud ou de lui même

    /descendant-or-self::node()/ => //
    /descendant-or-self::node()/telephones => //telephones

    //telephones/preceding-sibling::adresse/pays

    Quelques abbréviation

    /descendant-or-self::node()/ => //

    self::node() => .

    /repertoire/personne/adresse/self::node()
    /repertoire/personne/adresse/. 
    //adresse/.

    Vers un noeud parent en chemin relatif

    parent::node() => ..

    //email/../../telephones/telephone

    Prédicats

    téléphone avec l'attribut type = bureau depuis email

    //email/../../telephones/telephone[attribute::type="bureau"]

    il existe des wildcards, par exemple le caractère * représente n'importe quelle suite de caractère

    //*[attribute::type] => mauvaise méthode car on récupère tous les noeud possedant un attribut nommé type

    une bonne méthode 
    //telephone[attribute::type="bureau"]

    ! => non (abbreviation de not() )
    tous les téléphone non fixe

    //telephone[not(attribute::type="fixe")]

    //telephone[attribute::type!="fixe"]

    tous les telephone non fixe et non professionnel

    //telephone[not(attribute::type="fixe")][not(attribute::type="bureau")]

    //telephone[attribute::type!="fixe"][attribute::type!="bureau"]

    dernier élément telephone

    /descendant::telephone[last()]

    tous les derniers éléments telephone
    //telephone[last()]

    position() => la position (de 1 à x) des éléments dans la liste xpath
    last() le dernier élément de la liste
    les balises telephone dont la position est strictement inférieure à la valeur de la position de la dernière balise de la liste
    /descendant::telephone[position() < last()]

    Position : premier élément telephone
    /descendant::telephone[position() = 1]

    compter tous les éléments d'un xml

    count(//*) compte tous les noeuds du xml
    count(//text()) compte tous les noeuds texte du xml
    count(//comment()) compte tous les noeuds commentaires du xml
    count(//telephone) compte tous les noeuds telephone du xml

    count(/descendant::telephone[last()]) compte tous les noeud qui sont "le dernier noeud telephone" 0 (s'il n'y en a pas) ou 1

    Abreviation
    les attributs peuvent être abrégé avec de attribute:: à @

    /descendant::telephone[attribute::type!="professionnel"][attribute::type!="bureau"]

    /descendant::telephone[@type!="professionnel"][@type!="bureau"]

    //telephone[@type!="professionnel"][@type!="bureau"]

-->
